### ISSUE TITLE
Browsing to https://shipit.mozilla-releng.net/ returns an empty page

### ISSUE THREAD

**Issue by JohanLorenzo** [mozilla-releng/shipit#106]
@jcristau came to me because he cannot use ship-it prod. It returns an empty page. To be more precise, he noticed the console outputs `Error: "Missing required option "url""`. I reproduce the problem too:
<img width="346" alt="image" src="https://user-images.githubusercontent.com/5907366/70045326-337fac80-15c4-11ea-91d4-5b2676254eb7.png">

I looked at the stacktrace and it seems the error is at 
https://github.com/mozilla-releng/shipit/blob/aa281759280a93ea2bbda3739acb5802ee76d5d4/frontend/src/components/auth/UserSession.js#L42 

It looks like a regression coming from https://github.com/mozilla-releng/shipit/pull/78.

What do you think @rail ?

In the meantime, @jcristau and I are both able to work around the problem by opening the link in a private window.

**Comment by rail** [comment]
Some people hit this before... Cleaning the local storage for this site helped.

`this.url` is supposed to be assigned via [this](https://github.com/mozilla-releng/shipit/blob/aa281759280a93ea2bbda3739acb5802ee76d5d4/frontend/src/components/auth/UserSession.js#L36), then [the static constructor](https://github.com/mozilla-releng/shipit/blob/aa281759280a93ea2bbda3739acb5802ee76d5d4/frontend/src/components/auth/UserSession.js#L48) or [local storage](https://github.com/mozilla-releng/shipit/blob/aa281759280a93ea2bbda3739acb5802ee76d5d4/frontend/src/components/auth/UserSession.js#L60). With fresh local storage (like in your case in a private window), it works [perfectly fine](https://github.com/mozilla-releng/shipit/blob/049307c1a7dd053225d8a3bdaed84bfa2be73054/frontend/src/components/auth/auth0.js#L27).

We should use the values from local storage explicitly I guess.

**Comment by jcristau** [comment]
Indeed clearing site storage helps.

**Comment by rail** [comment]
Looks like everybody refreshed the local storage.

**Comment by srfraser** [comment]
Affected me, too, today.
