### ISSUE TITLE
can't schedule `ship` phase for rally-core-addon 1.4.2 build1 and 1.4.3 build1

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/shipit#1065]
Not quite sure what's going on here.

Rally-core-addon 1.4.2 and 1.43 build1 both appear to have the required number of signoffs for the `ship` phase, but they aren't shipping.

- have we changed something in the UI or db so the addon has a different set of required signoffs than the UI shows? (why isn't the `ship` graph launching?
- can we schedule the `ship` graph manually to mark the releases as shipped?

**Comment by escapewindow** [comment]
Related: #1006

**Comment by jcristau** [comment]
For the record:
```
$ curl https://shipit-api.mozilla-releng.net/xpi/signoff/rally-core-addon-1.4.3-build1/ship
{
  "signoffs": [
    {
      "completed": "2022-05-05T12:15:55.321789Z",
      "completed_by": "pkewisch@mozilla.com",
      "description": "Ship XPI",
      "name": "Privileged webextension admin",
      "permissions": "xpi_privileged_signoff",
      "signed": true,
      "uid": "NPOmMSESQB6kqCrpEBsAfg"
    }
  ]
}
$ curl https://shipit-api.mozilla-releng.net/xpi/signoff/rally-core-addon-1.4.2-build1/ship
{
  "signoffs": [
    {
      "completed": "2022-05-05T12:15:44.323520Z",
      "completed_by": "pkewisch@mozilla.com",
      "description": "Ship XPI",
      "name": "Privileged webextension admin",
      "permissions": "xpi_privileged_signoff",
      "signed": true,
      "uid": "S5-Gt9fNSAGsmPWCV1q7SQ"
    }
  ]
}
```

In the logs I see a PUT to `/xpi/signoff/rally-core-addon-1.4.3-build1/ship` with a 400 response at `2022-05-05T12:15:47.841288Z`, but I'm not seeing an explanation.  Same for 1.4.2 at `2022-05-05T12:15:36.881171Z`. Nothing in sentry, AFAICT.

**Comment by jcristau** [comment]
Required permission for signoff:
https://github.com/mozilla-releng/shipit/blob/3ef352a9e6babcbfdc2681b276301f8280f5bd66/api/src/shipit_api/common/config.py#L501
Corresponding group is defined here:
https://github.com/mozilla-releng/shipit/blob/3ef352a9e6babcbfdc2681b276301f8280f5bd66/api/src/shipit_api/admin/settings.py#L86
And granted the `phase_signoff` and `schedule_phase` scopes:
https://github.com/mozilla-releng/shipit/blob/3ef352a9e6babcbfdc2681b276301f8280f5bd66/api/src/shipit_api/admin/settings.py#L187-L192

As far as I can tell these haven't changed recently.

**Comment by escapewindow** [comment]
Well, maybe this is a training opportunity for "how to craft a `ship` flavor relpro graph manually".

**Comment by escapewindow** [comment]
Shipped.
