### ISSUE TITLE
"Ship" phase has red exclamation mask and is not completed

### ISSUE THREAD

**Issue by wagnerand** [mozilla-releng/shipit#1067]
I triggered the "ship" phase for a privileged extension, but it looks like something went wrong.

<img width="861" alt="shipit" src="https://user-images.githubusercontent.com/873258/167886666-942ef11e-66ff-46b6-85cc-55871b2d7ed6.png">

What does this mean?
How can we complete this phase?

**Comment by escapewindow** [comment]
https://firefox-ci-tc.services.mozilla.com/tasks/ZOBm1UCnQBmIS47hFpz46g/runs/0/logs/public/logs/live.log

```
[task 2022-05-10T11:15:34.523Z] 2022-05-10 11:15:34,523 - ERROR - Client ID task-client/ZOBm1UCnQBmIS47hFpz46g/0/on/us-east-1/i-015496c45a2246fc1/until/1652182529.779 does not have sufficient scopes and is missing the following scopes:
[task 2022-05-10T11:15:34.523Z] 
[task 2022-05-10T11:15:34.523Z] ```
[task 2022-05-10T11:15:34.523Z] project:xpi:releng:github:project:mozilla-rally/rally-core-addon
[task 2022-05-10T11:15:34.523Z] ```
```

Probably the root cause for #1065 as well.

**Comment by escapewindow** [comment]
https://phabricator.services.mozilla.com/D146125

**Comment by escapewindow** [comment]
I'm now guessing that the previous rally-core releases did have a red exclamation mark, and then the action task aged off?

**Comment by wagnerand** [comment]
@escapewindow Previous releases did not have that. I am sure because I shipped a few old versions this week without any issues.

**Comment by escapewindow** [comment]
I was able to mark them as shipped via a manually crafted relpro action. https://docs.mozilla-releng.net/en/latest/taskcluster/testing_relpro.html
