### ISSUE TITLE
Phases complete and shown as successful even if a task fails

### ISSUE THREAD

**Issue by wagnerand** [mozilla-releng/shipit#1077]
Recently, I triggered the "Ship" phase for firefox-translations-1.1.2-build which completed according to shipit:

<img width="870" alt="Screenshot 2022-05-30 at 11 57 08" src="https://user-images.githubusercontent.com/873258/170968079-6d5b7db1-9068-4d22-a045-eb4cb102e8a5.png">

However, looking at the [task group](https://firefox-ci-tc.services.mozilla.com/tasks/groups/aDyKlA2TRC6N5XrdhtBJJw) in task cluster, one task has failed:

<img width="943" alt="Screenshot 2022-05-30 at 11 58 17" src="https://user-images.githubusercontent.com/873258/170968279-eb050f55-6c31-489c-a23f-afb78b5e63b4.png">

---

Similarly, the a build for searchengine-devtools failed (https://firefox-ci-tc.services.mozilla.com/tasks/groups/SzR0NU1xThGCnCKdi2Datw), but shipit showed completed and even allowed me to sign off on it. I have canceled that build in the meantime. The same goes for a recent remote-settings-devtools build

<img width="866" alt="Screenshot 2022-05-30 at 12 06 07" src="https://user-images.githubusercontent.com/873258/170969676-04c2e52c-bf29-4e02-be16-4600b51ce9e7.png">

In the [task-group,](https://firefox-ci-tc.services.mozilla.com/tasks/groups/QZ70Id9WRLiLQ3JDoye6aA) the linter task failed:

<img width="1229" alt="Screenshot 2022-05-30 at 12 07 04" src="https://user-images.githubusercontent.com/873258/170969847-7855caef-348f-4344-a6e4-96283087fdf8.png">

**Comment by escapewindow** [comment]
This is the current behavior: relman, sheriffs, and releng watch the graphs to make sure they go green. So one way would be to require addons reviews/signoffs to include a green task group check.

We could add a shipit task in each phase that marks the phase as completed, but a) there are some cases where non-blocking leaf nodes fail in the Firefox release graph and we decide that that's ok, so we can't make it a hard failure; and b) we'll have to slot that into Releng's current priorities.

**Comment by wagnerand** [comment]
Thank you. I believe blocking would be ideal for add-ons. If that is not feasible or takes a long time, could we start by non-blocking, but showing something other than the blue checkmark on shipit? This would help users to immediately see if something requires their attention, without having to (remember to) inspect the tasks every time.

**Comment by gabrielBusta** [comment]
I started taking a stab at this yesterday. I think both are feasible. I'd need to make changes to keep track of the release phase status.

- The shipit back-end changes to add a phase status API might look like [this](https://github.com/mozilla-releng/shipit/pull/1087)
- Calling a phase status API from shipitscript might look like [this](https://github.com/mozilla-releng/scriptworker-scripts/pull/521)

**Comment by gabrielBusta** [comment]
#1087
