### ISSUE TITLE
create production database dumps to make local testing easier

### ISSUE THREAD

**Issue by bhearsum** [mozilla-releng/shipit#1431]
Testing certain types of changes to ship it (product details generation, ui changes) can be difficult without proper data in the Ship It database. Even if you create _some_ data in the database, it's difficult to ensure you have all of the different types of data you need to robustly test.

The solution we've used for this [elsewhere](https://github.com/mozilla/balrog) is to create [nightly database dumps of the production database](https://github.com/mozilla-releng/balrog/blob/4bd60d02da55d0180856f9b6664034e3f1cfbe19/scripts/manage-db.py#L125), and [import them at first run for local dev](https://github.com/mozilla-releng/balrog/blob/4bd60d02da55d0180856f9b6664034e3f1cfbe19/scripts/initdb_and_run.sh#L7-L19)

In Balrog, the database is large enough, and contains some permission/ACL informations, that we need to selectively dump it. Ship It's database is small enough and contains no sensitive data, so we should be able to dump the entire database, which simplifies things.

**Comment by gabrielBusta** [comment]
Reminds me of #1396

**Comment by bhearsum** [comment]
> Reminds me of #1396

Indeed! We could easily fix that once we have database dumps.

**Comment by gabrielBusta** [comment]
SRE wired up Nightly dumps. Can we call this closed? Sounds like #1396 is about getting the dumps in the local dev env

**Comment by bhearsum** [comment]
> SRE wired up Nightly dumps. Can we call this closed? Sounds like #1396 is about getting the dumps in the local dev env

Sounds good to me - thank you!
