### ISSUE TITLE
Firefox-android listed twice on Firefox Pending Releases

### ISSUE THREAD

**Issue by DonalMe** [mozilla-releng/shipit#1432]
This only seems to happen since firefox-android repo migrated to mozilla-central/mozilla.beta
Did not see this will 125.0 builds

![image](https://github.com/mozilla-releng/shipit/assets/76789979/1c97970b-84a9-41f2-8c5f-a7d2745121f8)

**Comment by jcristau** [comment]
I remember seeing this on try.  I think it's a side effect of having firefox-android both on github (for 125) and hg (for 126+), so it'll go away once 125 is EOL and we remove github from the config, but it might be worth fixing anyway...
