### ISSUE TITLE
make partials optional in stage

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/shipit#222]
[These lines](https://github.com/mozilla-releng/shipit/blob/99b0de7cb714bf792c93fe9e3a5269216e04ebe3/frontend/src/views/NewRelease/index.js#L50-L51) appear to conflate `enablePartials` and `requirePartials`. We may want to add `requirePartials` as a release property. I believe this will allow us to make partials optional in staging, but required in production?

**Comment by rail** [comment]
I'm going to look at this and a toggle for partials in staging.

**Comment by rail** [comment]
This is done.
