### ISSUE TITLE
Split `privileged` group

### ISSUE THREAD

**Issue by wagnerand** [mozilla-releng/shipit#287]
The `privileged` group is quite broad with lots of different users that are responsible for different things.

Let's split that group into:
* ~~privileged-amo~~ privileged
* ~~privileged-normandy~~ normandy-privileged

For ~~privileged-amo~~ _privileged_, the following people should be allowed to sign off:
* awagner@mozilla.com
* pkewisch@mozilla.com

For ~~privileged-normandy~~ _normandy-privileged_, the following people should be allowed to sign off:
* dharvey@mozilla.com
* jkerim@mozilla.com
* mbanner@mozilla.com
* mcooper@mozilla.com
* rdalal@mozilla.com
* ttran@mozilla.com
(@mythmon and @rehandalal could you double check that list, please?)

**Comment by escapewindow** [comment]
We already have `mozillaonline-privileged`; we may want to continue that pattern of naming (`amo-privileged` and `normandy-privileged`). This will take xpi-manifest changes as well as shipit.

Until we land this, we could enforce this via policy+auditing: don't sign off on things that you shouldn't. The downside of this is policy allows for behavior that shouldn't be allowed. The upside is it takes no additional coding, and we can get there via documentation.

**Comment by rail** [comment]
Just realized that this also requires us changing https://github.com/mozilla-extensions/xpi-manifest/blob/master/xpi-manifest.yml and add a new `addon-type` enum value for these groups and land the changes in sync. Can someone split the existing privileged addons into privileged-amo and privileged-normandy as a PR or a list of extensions that can be turned into a PR?

**Comment by escapewindow** [comment]
https://github.com/mozilla-extensions/xpi-manifest/pull/67 has the xpi-manifest changes needed. We are currently blocked on a naming decision, and updated docs. Once that happens and these two PRs match, we can land both.

The [xpi-template PR](https://github.com/mozilla-extensions/xpi-template/pull/18) doesn't strictly need to land at the same time, but has the same naming decision blocker.
