### ISSUE TITLE
Self signoff shouldn't be allowed

### ISSUE THREAD

**Issue by wagnerand** [mozilla-releng/shipit#289]
Even if a user has permission to build and promote, they shouldn't be allowed to promote their own build.

**Comment by rail** [comment]
This can be implemented (or worked around) by adding an extra signoff. Instead of having 2 signoffs and not letting the originator to signoff, we can have 3 signoffs and ask the originator to signoff as a sign that this is ready to go. What do you think?

**Comment by escapewindow** [comment]
Hm. I think the 2nd signoff prevents self-signoff abuse.

**Comment by rail** [comment]
Good point. Unless we explicitly want to exclude the originator from the signoff process for some reason, we are good with the current approach, which should prevent us from a bad actor case (the main reason behind multiple signoffs).

**Comment by bhearsum** [comment]
I'm closing this because a second signoff is a good enough workaround IMO.
