### ISSUE TITLE
show metadata about a release

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/shipit#426]
Which revision should be the minimum. All of the inputs going into the action task might be nice. This goes for the current releases and recent releases views.

**Comment by escapewindow** [comment]
See also: #295 . Requestor, signoff users, and a comment field would be awesome.

**Comment by Fenn-CS** [comment]
Hello @escapewindow @bhearsum , I would like to work on this. Can I get some more context and get a go-head?

**Comment by escapewindow** [comment]
@Fenn-CS Awesome! @bhearsum is willing to mentor. First step is probably setting up your local environment, per the [readme](https://github.com/mozilla-releng/shipit/blob/main/README.rst).

**Comment by escapewindow** [comment]
<img width="867" alt="current_releases_view" src="https://user-images.githubusercontent.com/826343/101831839-5f911000-3aeb-11eb-9788-bd8b645e10cf.png">

Here are some thoughts about metadata we could expose in the `Releases` and `Recent Releases` views. I'm open about what this looks like.

**Comment by Fenn-CS** [comment]
Thank you @escapewindow and yes! am very happy with the mentorship from @bhearsum thank you in advance! Meanwhile my local environment is already setup but I get `Error contacting Shipit backend: Error: Network Error. Are you connected to the VPN?` on the homescreen.

**Comment by escapewindow** [comment]
Filed #553.

**Comment by escapewindow** [comment]
@Fenn-CS are you still working on this?

**Comment by Fenn-CS** [comment]
@escapewindow Unfortunately no, there were several things mostly permissions that I needed to work that was/is unfortunately not easily available.

**Comment by escapewindow** [comment]
Sorry to hear. Thanks for giving it a try!

**Comment by sarah-clements** [comment]
@bhearsum could you weigh in on what Aki mentioned in [this comment](https://github.com/mozilla-releng/shipit/issues/426#issuecomment-742810686) about displaying signoffs (presumably I'd use data from the `signoff` API?) and what signoffs are remaining. Could you clarify a bit what "remaining signoffs" would refer to?

**Comment by bhearsum** [comment]
> @bhearsum could you weigh in on what Aki mentioned in [this comment](https://github.com/mozilla-releng/shipit/issues/426#issuecomment-742810686) about displaying signoffs (presumably I'd use data from the `signoff` API?) and what signoffs are remaining. Could you clarify a bit what "remaining signoffs" would refer to?

Sure! I'm not sure what your level of existing knowledge here, so forgive me if you know some of this already. While looking into this, I realized that we don't _have_ any required signoffs for Firefox, so for this part, we'll have to focus on XPIs, where we do have them.

With that in mind, you'll need to set `GITHUB_TOKEN`, restart the app, and create an XPI release (this should be easier than creating the Firefox one!). Once that's done, loading https://localhost:8010/xpi will query a few endpoints:
* https://localhost:8015/xpi/releases will return all non-completed XPI releases, as well as their phases
* For each phase of each release, an endpoint like https://localhost:8015/xpi/signoff/bergamot-browser-extension-0.4.0-build1/ship will be queried, which returns data with both completed and required signoff information in it, like:
```
{
  "signoffs": [
    {
      "completed": "",
      "completed_by": "",
      "description": "Ship XPI",
      "name": "Normandy privileged admin",
      "permissions": "xpi_normandy-privileged_signoff",
      "signed": false,
      "uid": "QZMLn5FmTUuEXsOwezHSjg"
    }
  ]
}
```

This list will have an entry for each group ("name" in the JSON) that needs to signoff. `completed_by` will contain the username of the person who made that signoff, if they've done so.

I _think_ you were just asking about this part, but I think all of the information mentioned in Aki's mockup is in one of the two above endpoints. If there's anything else unclear just let me know!
