### ISSUE TITLE
ryanvm couldn't schedule an RC ship phase

### ISSUE THREAD

**Issue by bhearsum** [mozilla-releng/shipit#449]
"Error: required permission: project:releng:services/shipit_api/schedule_phase/firefox/ship_firefox_rc, user permissions: "

He's been able to do this in the past. We recently made some changes to permissions (possibly between the previous RC and this one), and also did some dependency updates.

**Comment by mozbhearsum** [comment]
i tried to debug this from a bunch of angles. the best theory at the moment is that the token didn't refresh properly in the background. i couldn't repro in staging, but that stuff is finnicky. ryan will try again with RC2 and we'll see what happens.

**Comment by mozbhearsum** [comment]
> i tried to debug this from a bunch of angles. the best theory at the moment is that the token didn't refresh properly in the background. i couldn't repro in staging, but that stuff is finnicky. ryan will try again with RC2 and we'll see what happens.

worked fine for rc2, i'm going with this theory for now, and deprioritizing any further debugging (a refresh or logout/login will fix it).

**Comment by jmaher** [comment]
as ryanvm has shipped many releases, I am going to assume this is not really an issue.
