### ISSUE TITLE
Fenix builds not listed on the Recent Releases page

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla-releng/shipit#620]
Go to https://shipit.mozilla-releng.net/recent
Fenix Beta is not listed while we created it

**Comment by bhearsum** [comment]
https://github.com/mozilla-releng/shipit/pull/622 should fix this.

**Comment by bhearsum** [comment]
Looks like it worked. I see at least one Fenix & A-C on https://shipit.mozilla-releng.net/recent

**Comment by pascalchevrel** [comment]
Thanks!
