### ISSUE TITLE
`docker-compose up` is busted in latest docker hub images

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/shipit#750]
This appears to be busted in both `python:3.8.10` and `python:3.8.9`. `python:3.8.8` appears to work.
Because we have `FROM python:3.8`, I imagine that tag has been moved to point at `python:3.8.10`, which is busted.

A workaround is to change `api/Dockerfile` to `FROM python:3.8.8` .
We may want to instead re-pin the requirements with a newer `python:3.8` image.

**Comment by bhearsum** [comment]
Should be fixed by #752.
