### ISSUE TITLE
Commit link points to the wrong repo and commit

### ISSUE THREAD

**Issue by wagnerand** [mozilla-releng/shipit#828]
<img width="873" alt="Screenshot 2021-07-30 at 12 44 14" src="https://user-images.githubusercontent.com/873258/127641986-99b1452c-557a-4720-8d94-a1c8aa16756c.png">

The [commit link](https://github.com/mozilla-extensions/xpi-manifest/commit/3029cf2130adb04ac01b37e6ebd222052e1e3598) for the release shown in the screenshot above should point to https://github.com/mozilla-extensions/restore-search-defaults/commit/10fd472d1b092acfb18d31529a44e7b8de01aa09

**Comment by MihaiTabara** [comment]
CC @sarah-clements @jmaher who have recently done work in that space.

**Comment by jmaher** [comment]
I have a WIP PR up here: https://github.com/mozilla-releng/shipit/pull/829

**Comment by bhearsum** [comment]
Did #829 fix this, @jmaher?

**Comment by jmaher** [comment]
it sort of did, was backed out because we were seeing issues on all views in shipit with missing data.  This is something I would like to pick back up since I am probably 95% to a proper solution with #829

**Comment by wagnerand** [comment]
I believe this is still an issue. A recent release of the Rally core add-on still points to https://github.com/mozilla-extensions/xpi-manifest/commit/9c23a20ea45714f9f80609ec43ed36175078ad60.

**Comment by jmaher** [comment]
I have a fix awaiting review:
https://github.com/mozilla-releng/shipit/pull/956

**Comment by MihaiTabara** [comment]
With https://github.com/mozilla-releng/shipit/pull/956 I believe we can close this?

**Comment by jmaher** [comment]
When this is in production we can close it!

**Comment by jmaher** [comment]
in production
